name: Deploy Docker Image to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t  ${{ secrets.DOCKER_USERNAME }}/osm-reader:latest .

      - name: Push Docker image
        run: docker push  ${{ secrets.DOCKER_USERNAME }}/osm-reader:latest
        
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}

      - uses: actions-hub/kubectl@master
        with:
          args: get pods

      - name: Deploy to Kubernetes
        uses: actions-hub/kubectl@master
        with:
          args: apply -f deploy.yaml
